### ISSUE TITLE
Flesh out step types docs

### ISSUE THREAD

**Issue by jilleJr** [iver-wharf/iver-wharf.github.io#30]
The step types docs are very basic at the moment. Using solely a code block to describe everything.

This is fine for us internally, but does not show a greater grasp over how these step types work.

Suggested convention:

````md
<!-- panels:start -->

<!-- div:left-panel -->

# Container step

Short description of what it does.

Longer description of how it works.

<!-- div:right-panel -->

## Minimal example

```yaml
myStage:
  myStep:
    container:
      image: alpine:latest
      cmds:
        - echo 'hello world'
```

<!-- panels:end -->

<!-- panels:start -->

<!-- div:left-panel -->

## Parameters

### `image`

Type: `string`

Short description of what it does

```yaml
image: alpine:latest
```

### `cmds`

Type: `string array`

Short description of what it does

```yaml
cmds:
  - echo 'hello world'
```

<!-- div:right-panel -->

## Full example

```yaml
myStage:
  myStep:
    container:
      image: alpine:latest
      cmds:
        - echo 'hello world'
      os: linux/windows
      shell: /bin/sh
      secretName: mysecret
      serviceAccount: default
      certificatesMountPath: /usr/local/share/ca-certificates
```

<!-- panels:end -->
````

Preview:

![Screenshot_2021-05-20_09-43-40](https://user-images.githubusercontent.com/2477952/118939415-efb36b00-b94f-11eb-945e-1cae74ed7aa6.png)
